Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ENV['GOPATH'], "/media/sf_GOPATH0", SharedFoldersEnableSymlinksCreate: false
  config.ssh.keep_alive = true

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.provision "shell", path: "../pre.sh", privileged: false, env: {"OS" => "linux", "DOCKER" => "true"}

  config.vm.define "linux" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:linux"
    end
  end

  config.vm.define "android" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:android"
    end
  end

  config.vm.define "windows_32_shared" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:windows_32_shared"
    end
  end

  config.vm.define "windows_32_static" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:windows_32_static"
    end
  end

  config.vm.define "windows_64_shared" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:windows_64_shared"
    end
  end

  config.vm.define "windows_64_static" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:windows_64_static"
    end
  end

  config.vm.define "rpi1" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:rpi1"
    end
  end

  config.vm.define "rpi2" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:rpi2"
    end
  end

  config.vm.define "rpi3" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:rpi3"
    end
  end

  config.vm.define "sailfish" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:sailfish"
    end
  end

  config.vm.define "ubports_arm_vivid" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:ubports_arm_vivid"
    end
  end

  config.vm.define "ubports_64_vivid" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:ubports_64_vivid"
    end
  end

  config.vm.define "ubports_arm_xenial" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:ubports_arm_xenial"
    end
  end

  config.vm.define "ubports_64_xenial" do |m|
    config.vm.provision "docker" do |d|
      d.pull_images "therecipe/qt:ubports_64_xenial"
    end
  end

end
