// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/types.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GlobalData struct {
	UserStateMap         map[string]*State `protobuf:"bytes,1,rep,name=userStateMap,proto3" json:"userStateMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CurrentUser          string            `protobuf:"bytes,2,opt,name=currentUser,proto3" json:"currentUser,omitempty"`
	InternalServerPort   int64             `protobuf:"varint,3,opt,name=internalServerPort,proto3" json:"internalServerPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GlobalData) Reset()         { *m = GlobalData{} }
func (m *GlobalData) String() string { return proto.CompactTextString(m) }
func (*GlobalData) ProtoMessage()    {}
func (*GlobalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7311ad31e6b1ce7e, []int{0}
}

func (m *GlobalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalData.Unmarshal(m, b)
}
func (m *GlobalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalData.Marshal(b, m, deterministic)
}
func (m *GlobalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalData.Merge(m, src)
}
func (m *GlobalData) XXX_Size() int {
	return xxx_messageInfo_GlobalData.Size(m)
}
func (m *GlobalData) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalData.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalData proto.InternalMessageInfo

func (m *GlobalData) GetUserStateMap() map[string]*State {
	if m != nil {
		return m.UserStateMap
	}
	return nil
}

func (m *GlobalData) GetCurrentUser() string {
	if m != nil {
		return m.CurrentUser
	}
	return ""
}

func (m *GlobalData) GetInternalServerPort() int64 {
	if m != nil {
		return m.InternalServerPort
	}
	return 0
}

type State struct {
	Token                string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Settings             *StateSetting     `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	PanCookie            []*Cookies        `protobuf:"bytes,3,rep,name=panCookie,proto3" json:"panCookie,omitempty"`
	UserStorage          map[string]string `protobuf:"bytes,4,rep,name=userStorage,proto3" json:"userStorage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Username             string            `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Uk                   string            `protobuf:"bytes,6,opt,name=uk,proto3" json:"uk,omitempty"`
	Logout               bool              `protobuf:"varint,7,opt,name=logout,proto3" json:"logout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_7311ad31e6b1ce7e, []int{1}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *State) GetSettings() *StateSetting {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *State) GetPanCookie() []*Cookies {
	if m != nil {
		return m.PanCookie
	}
	return nil
}

func (m *State) GetUserStorage() map[string]string {
	if m != nil {
		return m.UserStorage
	}
	return nil
}

func (m *State) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *State) GetUk() string {
	if m != nil {
		return m.Uk
	}
	return ""
}

func (m *State) GetLogout() bool {
	if m != nil {
		return m.Logout
	}
	return false
}

type StateSetting struct {
	DownloadSegSize      int64    `protobuf:"varint,1,opt,name=downloadSegSize,proto3" json:"downloadSegSize,omitempty"`
	DownloadCoroutine    int64    `protobuf:"varint,2,opt,name=downloadCoroutine,proto3" json:"downloadCoroutine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateSetting) Reset()         { *m = StateSetting{} }
func (m *StateSetting) String() string { return proto.CompactTextString(m) }
func (*StateSetting) ProtoMessage()    {}
func (*StateSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_7311ad31e6b1ce7e, []int{1, 0}
}

func (m *StateSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateSetting.Unmarshal(m, b)
}
func (m *StateSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateSetting.Marshal(b, m, deterministic)
}
func (m *StateSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateSetting.Merge(m, src)
}
func (m *StateSetting) XXX_Size() int {
	return xxx_messageInfo_StateSetting.Size(m)
}
func (m *StateSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_StateSetting.DiscardUnknown(m)
}

var xxx_messageInfo_StateSetting proto.InternalMessageInfo

func (m *StateSetting) GetDownloadSegSize() int64 {
	if m != nil {
		return m.DownloadSegSize
	}
	return 0
}

func (m *StateSetting) GetDownloadCoroutine() int64 {
	if m != nil {
		return m.DownloadCoroutine
	}
	return 0
}

type Cookies struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Expires              int64    `protobuf:"varint,4,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cookies) Reset()         { *m = Cookies{} }
func (m *Cookies) String() string { return proto.CompactTextString(m) }
func (*Cookies) ProtoMessage()    {}
func (*Cookies) Descriptor() ([]byte, []int) {
	return fileDescriptor_7311ad31e6b1ce7e, []int{2}
}

func (m *Cookies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cookies.Unmarshal(m, b)
}
func (m *Cookies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cookies.Marshal(b, m, deterministic)
}
func (m *Cookies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cookies.Merge(m, src)
}
func (m *Cookies) XXX_Size() int {
	return xxx_messageInfo_Cookies.Size(m)
}
func (m *Cookies) XXX_DiscardUnknown() {
	xxx_messageInfo_Cookies.DiscardUnknown(m)
}

var xxx_messageInfo_Cookies proto.InternalMessageInfo

func (m *Cookies) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Cookies) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Cookies) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Cookies) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func init() {
	proto.RegisterType((*GlobalData)(nil), "storage.globalData")
	proto.RegisterMapType((map[string]*State)(nil), "storage.globalData.UserStateMapEntry")
	proto.RegisterType((*State)(nil), "storage.state")
	proto.RegisterMapType((map[string]string)(nil), "storage.state.UserStorageEntry")
	proto.RegisterType((*StateSetting)(nil), "storage.state.setting")
	proto.RegisterType((*Cookies)(nil), "storage.cookies")
}

func init() { proto.RegisterFile("storage/types.proto", fileDescriptor_7311ad31e6b1ce7e) }

var fileDescriptor_7311ad31e6b1ce7e = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xb3, 0x4d, 0x9c, 0x4c, 0x50, 0x49, 0x87, 0xaa, 0x5a, 0xe5, 0x82, 0x55, 0x81, 0xe4,
	0x03, 0x32, 0x52, 0xb8, 0x20, 0x0e, 0x48, 0xa8, 0x70, 0xe0, 0x80, 0x40, 0x6b, 0xf5, 0x03, 0xb6,
	0xc9, 0xc8, 0xb2, 0xec, 0xee, 0x5a, 0xbb, 0xeb, 0x42, 0xf8, 0x25, 0xfe, 0x90, 0x13, 0xf2, 0x7a,
	0xeb, 0xb8, 0x69, 0x0f, 0xdc, 0xf2, 0xde, 0xbc, 0x37, 0x3b, 0xf3, 0x26, 0x86, 0x17, 0xd6, 0x69,
	0x23, 0x0b, 0x7a, 0xeb, 0xf6, 0x0d, 0xd9, 0xac, 0x31, 0xda, 0x69, 0x8c, 0x03, 0x79, 0xf9, 0x37,
	0x02, 0x28, 0x6a, 0x7d, 0x23, 0xeb, 0xcf, 0xd2, 0x49, 0xfc, 0x0a, 0xcf, 0x5a, 0x4b, 0x26, 0x77,
	0xd2, 0xd1, 0x37, 0xd9, 0xf0, 0x28, 0x61, 0xe9, 0x72, 0xf3, 0x3a, 0x0b, 0xf2, 0xec, 0x20, 0xcd,
	0xae, 0x47, 0xba, 0x2f, 0xca, 0x99, 0xbd, 0x78, 0x60, 0xc5, 0x04, 0x96, 0xdb, 0xd6, 0x18, 0x52,
	0xae, 0x53, 0xf2, 0x49, 0x12, 0xa5, 0x0b, 0x31, 0xa6, 0x30, 0x03, 0x2c, 0x95, 0x23, 0xa3, 0x64,
	0x9d, 0x93, 0xb9, 0x23, 0xf3, 0x43, 0x1b, 0xc7, 0x59, 0x12, 0xa5, 0x4c, 0x3c, 0x51, 0x59, 0x7f,
	0x87, 0xb3, 0x47, 0x8f, 0xe2, 0x0a, 0x58, 0x45, 0x7b, 0x1e, 0xf9, 0xf6, 0xdd, 0x4f, 0x7c, 0x05,
	0xd3, 0x3b, 0x59, 0xb7, 0xe4, 0x9f, 0x5c, 0x6e, 0x4e, 0x87, 0xe1, 0x6d, 0x67, 0x14, 0x7d, 0xf1,
	0xc3, 0xe4, 0x7d, 0x74, 0xf9, 0x87, 0xc1, 0xd4, 0x93, 0x78, 0x0e, 0x53, 0xa7, 0x2b, 0x52, 0xa1,
	0x4f, 0x0f, 0x70, 0x03, 0x73, 0x4b, 0xce, 0x95, 0xaa, 0xb0, 0xa1, 0xd9, 0xc5, 0xc3, 0x66, 0x59,
	0x28, 0x8b, 0x41, 0x87, 0x19, 0x2c, 0x1a, 0xa9, 0xae, 0xb4, 0xae, 0x4a, 0xe2, 0xcc, 0xc7, 0xb7,
	0x1a, 0x4c, 0x5b, 0x4f, 0x5b, 0x71, 0x90, 0xe0, 0x27, 0x58, 0xf6, 0xb1, 0x79, 0x05, 0x3f, 0xf1,
	0x8e, 0x97, 0x47, 0xcf, 0x5c, 0x1f, 0x14, 0x7d, 0xd4, 0x63, 0x0f, 0xae, 0x61, 0xde, 0x41, 0x25,
	0x6f, 0x89, 0x4f, 0xfd, 0xfc, 0x03, 0xc6, 0x53, 0x98, 0xb4, 0x15, 0x9f, 0x79, 0x76, 0xd2, 0x56,
	0x78, 0x01, 0xb3, 0x5a, 0x17, 0xba, 0x75, 0x3c, 0x4e, 0xa2, 0x74, 0x2e, 0x02, 0x5a, 0x4b, 0x88,
	0xc3, 0x0a, 0x98, 0xc2, 0xf3, 0x9d, 0xfe, 0xa9, 0x6a, 0x2d, 0x77, 0x39, 0x15, 0x79, 0xf9, 0x9b,
	0x7c, 0x2a, 0x4c, 0x1c, 0xd3, 0xf8, 0x06, 0xce, 0xee, 0xa9, 0x2b, 0x6d, 0x74, 0xeb, 0x4a, 0xd5,
	0xa7, 0xce, 0xc4, 0xe3, 0xc2, 0xfa, 0x23, 0xac, 0x8e, 0xf7, 0x78, 0xe2, 0x7a, 0xe7, 0xe3, 0xeb,
	0x2d, 0xc6, 0xd7, 0xda, 0x42, 0x1c, 0xf2, 0xfb, 0x5f, 0x5b, 0xb7, 0xed, 0x4e, 0xdf, 0xca, 0x52,
	0xf9, 0x7f, 0xd5, 0x42, 0x04, 0x84, 0x1c, 0x62, 0xfa, 0xd5, 0x94, 0x86, 0x2c, 0x3f, 0xf1, 0xe3,
	0xde, 0xc3, 0x9b, 0x99, 0xff, 0x3e, 0xde, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xe7, 0x4b,
	0xda, 0x36, 0x03, 0x00, 0x00,
}
