Vagrant.configure("2") do |config|
  config.vm.box = "emil-appunite/macos10.13-xcode9.1"
  config.vm.network :private_network, ip: "192.168.10.2"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", SharedFoldersEnableSymlinksCreate: false
  config.vm.synced_folder ENV['GOPATH'], "/media/sf_GOPATH0", type: "nfs", SharedFoldersEnableSymlinksCreate: false
  config.ssh.keep_alive = true

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 8192
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.cpus = 1
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
  end

  config.vm.define "darwin" do |m|
    m.vm.provision "shell", path: "../pre.sh", privileged: false, env: {"OS" => "darwin", "DESKTOP" => "true"}
    m.vm.provision "shell", path: "../../ci/darwin.sh", privileged: false, env: {"OS" => "darwin", "DESKTOP" => "true"}
    m.vm.provision "shell", path: "../past.sh", privileged: false, env: {"OS" => "darwin", "DESKTOP" => "true"}
  end

  config.vm.define "homebrew" do |m|
    m.vm.provision "shell", path: "../pre.sh", privileged: false, env: {"OS" => "darwin", "DESKTOP" => "true", "QT_HOMEBREW" => "true"}
    m.vm.provision "shell", path: "../../ci/darwin.sh", privileged: false, env: {"OS" => "darwin", "DESKTOP" => "true", "QT_HOMEBREW" => "true"}
    m.vm.provision "shell", path: "../past.sh", privileged: false, env: {"OS" => "darwin", "DESKTOP" => "true", "QT_HOMEBREW" => "true"}
  end

  config.vm.define "android" do |m|
    m.vm.provision "shell", path: "../pre.sh", privileged: false, env: {"OS" => "darwin", "ANDROID" => "true"}
    m.vm.provision "shell", path: "../../ci/darwin.sh", privileged: false, env: {"OS" => "darwin", "ANDROID" => "true"}
    m.vm.provision "shell", path: "../past.sh", privileged: false, env: {"OS" => "darwin", "ANDROID" => "true"}
  end

  config.vm.define "ios" do |m|
    m.vm.provision "shell", path: "../pre.sh", privileged: false, env: {"OS" => "darwin", "IOS" => "true", "IOS_SIMULATOR" => "true"}
    m.vm.provision "shell", path: "../../ci/darwin.sh", privileged: false, env: {"OS" => "darwin", "IOS" => "true", "IOS_SIMULATOR" => "true"}
    m.vm.provision "shell", path: "../past.sh", privileged: false, env: {"OS" => "darwin", "IOS" => "true", "IOS_SIMULATOR" => "true"}
  end

  #TODO: desktop + webkit
  #TODO: android + openssl
  #TODO: sailfish
  #TODO: macports
  #TODO: nix

end
